import { useState } from 'react'
import {
  CheckCircle, XCircle, Lightbulb, TrendingUp, TrendingDown,
  Briefcase, Download, RefreshCw, ChevronDown, ChevronUp
} from 'lucide-react'
import ScoreRing from './ScoreRing'
import MiniBar from './MiniBar'

const ResultsDashboard = ({ data, onReset }) => {
  const [expandedSuggestion, setExpandedSuggestion] = useState(null)

  const handleDownload = () => {
    const lines = [
      '=== RESUME ANALYZER REPORT ===',
      '',
      `ATS Score: ${data.ats_score}/100`,
      `Role Match: ${data.role_match}`,
      '',
      '--- SUMMARY ---',
      data.summary,
      '',
      '--- STRENGTHS ---',
      ...(data.strengths || []).map(s => `• ${s}`),
      '',
      '--- WEAKNESSES ---',
      ...(data.weaknesses || []).map(w => `• ${w}`),
      '',
      '--- MISSING SKILLS ---',
      ...(data.missing_skills || []).map(s => `• ${s}`),
      '',
      '--- MATCHED SKILLS ---',
      ...(data.matched_skills || []).map(s => `✓ ${s}`),
      '',
      '--- SUGGESTIONS ---',
      ...(data.suggestions || []).map((s, i) => `${i + 1}. ${s.title}: ${s.description}`),
      '',
      '--- SUB-SCORES ---',
      `Keyword Density: ${data.keyword_density}%`,
      `Formatting: ${data.formatting_score}%`,
      `Experience Relevance: ${data.experience_relevance}%`,
      '',
      'Generated by ResumeAI — https://resumeai.vercel.app',
    ]
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'resume-analysis-report.txt'
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-6 animate-fade-up">
      {/* Top bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <div>
          <h2 className="text-xl font-display font-bold text-white">Analysis Complete</h2>
          <p className="text-sm text-white/40">Here's your detailed ATS report</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={handleDownload}
            className="flex items-center gap-2 px-4 py-2 text-xs font-medium text-white/60 hover:text-white glass rounded-xl transition-all hover:bg-white/5"
          >
            <Download size={14} />
            Download Report
          </button>
          <button
            onClick={onReset}
            className="flex items-center gap-2 px-4 py-2 text-xs font-medium text-brand-400 hover:text-brand-300 glass rounded-xl transition-all hover:bg-brand-500/10"
          >
            <RefreshCw size={14} />
            New Analysis
          </button>
        </div>
      </div>

      {/* Main score + sub scores */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Score Ring */}
        <div className="glass rounded-2xl p-6 flex flex-col items-center justify-center gap-4 glow">
          <ScoreRing score={data.ats_score} />
          <div className="text-center">
            <p className="text-xs text-white/30 font-mono uppercase tracking-widest">Role Match</p>
            <p className="text-sm font-semibold text-white/70 mt-1">{data.role_match}</p>
          </div>
        </div>

        {/* Sub scores */}
        <div className="glass rounded-2xl p-6 space-y-4">
          <h3 className="text-xs font-mono text-white/30 uppercase tracking-widest">Score Breakdown</h3>
          <MiniBar label="Keyword Density" value={data.keyword_density} delay={0} />
          <MiniBar label="Formatting Quality" value={data.formatting_score} delay={100} />
          <MiniBar label="Experience Relevance" value={data.experience_relevance} delay={200} />
        </div>

        {/* Summary */}
        <div className="glass rounded-2xl p-6 flex flex-col gap-3">
          <h3 className="text-xs font-mono text-white/30 uppercase tracking-widest">Summary</h3>
          <p className="text-sm text-white/60 leading-relaxed">{data.summary}</p>
        </div>
      </div>

      {/* Skills */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Missing skills */}
        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-4">
            <XCircle size={16} className="text-red-400" />
            <h3 className="text-sm font-semibold text-white/80">Missing Skills</h3>
            <span className="ml-auto text-xs px-2 py-0.5 rounded-full bg-red-500/10 text-red-400 font-mono">
              {data.missing_skills?.length || 0}
            </span>
          </div>
          <div className="flex flex-wrap gap-2">
            {(data.missing_skills || []).map((skill, i) => (
              <span
                key={i}
                className="skill-tag text-xs px-3 py-1.5 rounded-full font-medium"
                style={{
                  animationDelay: `${i * 80}ms`,
                  background: 'rgba(239,68,68,0.1)',
                  border: '1px solid rgba(239,68,68,0.2)',
                  color: '#fca5a5',
                }}
              >
                {skill}
              </span>
            ))}
          </div>
        </div>

        {/* Matched skills */}
        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-4">
            <CheckCircle size={16} className="text-brand-400" />
            <h3 className="text-sm font-semibold text-white/80">Matched Skills</h3>
            <span className="ml-auto text-xs px-2 py-0.5 rounded-full bg-brand-500/10 text-brand-400 font-mono">
              {data.matched_skills?.length || 0}
            </span>
          </div>
          <div className="flex flex-wrap gap-2">
            {(data.matched_skills || []).map((skill, i) => (
              <span
                key={i}
                className="skill-tag text-xs px-3 py-1.5 rounded-full font-medium"
                style={{
                  animationDelay: `${i * 80}ms`,
                  background: 'rgba(20,178,104,0.1)',
                  border: '1px solid rgba(20,178,104,0.2)',
                  color: '#6ee7b7',
                }}
              >
                {skill}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Strengths & Weaknesses */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp size={16} className="text-brand-400" />
            <h3 className="text-sm font-semibold text-white/80">Strengths</h3>
          </div>
          <ul className="space-y-2">
            {(data.strengths || []).map((s, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-white/60">
                <span className="text-brand-500 mt-0.5 flex-shrink-0">→</span>
                {s}
              </li>
            ))}
          </ul>
        </div>

        <div className="glass rounded-2xl p-6">
          <div className="flex items-center gap-2 mb-4">
            <TrendingDown size={16} className="text-amber-400" />
            <h3 className="text-sm font-semibold text-white/80">Weaknesses</h3>
          </div>
          <ul className="space-y-2">
            {(data.weaknesses || []).map((w, i) => (
              <li key={i} className="flex items-start gap-2 text-sm text-white/60">
                <span className="text-amber-500 mt-0.5 flex-shrink-0">→</span>
                {w}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Suggestions */}
      <div className="glass rounded-2xl p-6">
        <div className="flex items-center gap-2 mb-5">
          <Lightbulb size={16} className="text-amber-400" />
          <h3 className="text-sm font-semibold text-white/80">AI Suggestions</h3>
          <span className="ml-auto text-xs px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-400 font-mono">
            {data.suggestions?.length || 0} actions
          </span>
        </div>
        <div className="space-y-3">
          {(data.suggestions || []).map((s, i) => (
            <div
              key={i}
              className="rounded-xl bg-white/3 border border-white/5 overflow-hidden card-hover cursor-pointer"
              onClick={() => setExpandedSuggestion(expandedSuggestion === i ? null : i)}
            >
              <div className="flex items-center justify-between p-4">
                <div className="flex items-center gap-3">
                  <span className="w-6 h-6 rounded-lg bg-amber-500/10 flex items-center justify-center text-xs font-mono text-amber-400 flex-shrink-0">
                    {i + 1}
                  </span>
                  <span className="text-sm font-medium text-white/80">{s.title}</span>
                </div>
                {expandedSuggestion === i
                  ? <ChevronUp size={14} className="text-white/30" />
                  : <ChevronDown size={14} className="text-white/30" />
                }
              </div>
              {expandedSuggestion === i && (
                <div className="px-4 pb-4">
                  <p className="text-sm text-white/50 pl-9">{s.description}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}

export default ResultsDashboard
